# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Doo-IoT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Doo-IoT
  pod 'TTTAttributedLabel'
  pod 'SDWebImage', '~> 5.6.1'
  pod 'SwiftGifOrigin', '~> 1.7.0'
  pod 'TagListView'
  pod 'Toast-Swift'
  
  pod 'Alamofire'
  pod 'ReachabilitySwift'
  pod 'MaterialComponents/ActivityIndicator'
  pod 'SkeletonView'
  pod 'MQTTClient'

end
